[pytest]
testpaths =
    tests
    edge/nodes
norecursedirs =
    simulation
    docs
    tools/editor
    tools/cli
    scripts
    configs
    contracts
    dist
    node_modules
addopts = --import-mode=importlib
